# Generated by Django 5.2.9 on 2026-03-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='input',
            new_name='input_data',
        ),
    ]
