# Generated by Django 5.2.9 on 2026-03-05 02:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_rename_input_testcase_input_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['file_number', 'id']},
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='order',
        ),
        migrations.AddField(
            model_name='testcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='file_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
