# Generated by Django 5.2.12 on 2026-03-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_testcase_options_remove_testcase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='max_score',
            field=models.IntegerField(default=0, help_text="0 = ball tizimi yo'q (ICPC uslubi). >0 = Codeforces uslubi (500, 1000, 1500...)"),
        ),
        migrations.AddField(
            model_name='problem',
            name='score_decay_rate',
            field=models.FloatField(default=0.5, help_text='Har daqiqada kamayish koeffitsienti. max_score * (1 - decay * vaqt)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='wrong_penalty',
            field=models.IntegerField(default=50, help_text="Har noto'g'ri urinish uchun jarima (ball)"),
        ),
    ]
