# Generated by Django 5.2.12 on 2026-03-03 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Markdown formatida')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_rated', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Masala tartibi (A=0, B=1, ...)')),
                ('points', models.IntegerField(default=100)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='problems.problem')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('contest', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('penalty_count', models.IntegerField(default=0, help_text='ACCEPTED gacha WA soni')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submissions', to='contests.contest')),
                ('contest_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submissions', to='contests.contestproblem')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submission', to='submissions.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission__created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, help_text='Yechilgan masalalar soni')),
                ('penalty', models.IntegerField(default=0, help_text='ACM penalty (daqiqada)')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_virtual', models.BooleanField(default=False, help_text='Virtual ishtirok')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'penalty'],
                'unique_together': {('contest', 'user')},
            },
        ),
    ]
