# Generated by Django 5.2.12 on 2026-03-04 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestsubmission',
            options={'ordering': ['minutes_from_start']},
        ),
        migrations.RemoveField(
            model_name='contest',
            name='is_published',
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='label',
            field=models.CharField(default='A', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('contest', 'label'), ('contest', 'problem')},
        ),
        migrations.RemoveField(
            model_name='contestsubmission',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='contestsubmission',
            name='penalty_count',
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('icpc', 'ACM/ICPC'), ('rated', 'Rated'), ('virtual', 'Virtual'), ('unrated', 'Unrated')], default='icpc', max_length=20),
        ),
        migrations.AddField(
            model_name='contest',
            name='freeze_time',
            field=models.DateTimeField(blank=True, help_text='Scoreboard freeze boshlanadi', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_team_contest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_virtual_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='max_team_size',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='contests', through='contests.ContestProblem', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='rating_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('running', 'Running'), ('frozen', 'Frozen'), ('finished', 'Finished')], default='draft', max_length=20),
        ),

        migrations.AddField(
            model_name='contestproblem',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='minutes_from_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_rated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='contest_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contestproblem'),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RatingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rating', models.IntegerField()),
                ('new_rating', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_changes', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('invite_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='contests.contest')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_virtual', models.BooleanField(default=False)),
                ('solved_count', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0)),
                ('problem_results', models.JSONField(default=dict)),
                ('rank', models.IntegerField(default=0)),
                ('last_accept_time', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard', to='contests.contest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.team')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_virtual', models.BooleanField(default=False)),
                ('virtual_start', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_registrations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.team')),
            ],
            options={
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.team'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='contests.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='contest_teams', through='contests.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ContestParticipant',
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='points',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('contest', 'name')},
        ),
    ]
