# Generated by Django 5.2.12 on 2026-03-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_alter_contestsubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
