# Generated by Django 5.2.12 on 2026-03-05 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_fix_contest_cascades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingchange',
            options={'ordering': ['rank']},
        ),
        migrations.RenameField(
            model_name='ratingchange',
            old_name='created_at',
            new_name='calculated_at',
        ),
        migrations.AlterUniqueTogether(
            name='ratingchange',
            unique_together={('user', 'contest')},
        ),
        migrations.AddField(
            model_name='contest',
            name='rating_calculating',
            field=models.BooleanField(default=False, help_text='Hisoblash jarayonida (race condition himoyasi)'),
        ),
        migrations.AddField(
            model_name='contest',
            name='rating_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ratingchange',
            name='expected_rank',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ratingchange',
            name='new_rank_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ratingchange',
            name='old_rank_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ratingchange',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratingchange',
            name='solved_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ratingchange',
            name='delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ratingchange',
            name='new_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ratingchange',
            name='old_rating',
            field=models.IntegerField(default=0),
        ),
    ]
