# Generated by Django 5.2.12 on 2026-03-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_ratingchange_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='max_score',
            field=models.IntegerField(blank=True, help_text="Agar bo'sh bo'lsa problem.max_score ishlatiladi. Codeforces: 500, 1000, 1500, 2000, 2500, 3000", null=True),
        ),
        migrations.AddField(
            model_name='scoreboardentry',
            name='problem_scores',
            field=models.JSONField(default=dict, help_text='Har bir masala uchun ball tafsilotlari'),
        ),
        migrations.AddField(
            model_name='scoreboardentry',
            name='total_score',
            field=models.IntegerField(default=0, help_text='Jami ball (Codeforces uslubi)'),
        ),
    ]
