# Generated by Django 5.2.12 on 2026-03-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_rating',
            field=models.IntegerField(default=0),
        ),
    ]
