# Generated by Django 5.2.9 on 2026-03-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_max_rating'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='accommodation',
            field=models.CharField(blank=True, help_text="Yotoqxona / O'z uyi ...", max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='avg_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='education_form',
            field=models.CharField(blank=True, help_text='Kunduzgi / Sirtqi', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='education_lang',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, help_text='Bakalavr / Magistr', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty_id',
            field=models.IntegerField(blank=True, help_text='HEMIS dagi fakultet ID', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='group_id',
            field=models.IntegerField(blank=True, help_text='HEMIS dagi guruh ID', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='hemis_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='HEMIS tizimidagi talaba ID (integer)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hemis_refresh',
            field=models.TextField(blank=True, help_text='HEMIS refresh token', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hemis_student_id',
            field=models.CharField(blank=True, help_text='student_id_number (masalan 341241105193)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hemis_synced_at',
            field=models.DateTimeField(blank=True, help_text='HEMIS dan oxirgi sinc vaqti', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hemis_token',
            field=models.TextField(blank=True, help_text='HEMIS JWT token', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hemis_token_exp',
            field=models.DateTimeField(blank=True, help_text='Token eskirish vaqti', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hemis_user',
            field=models.BooleanField(default=False, help_text="HEMIS orqali ro'yxatdan o'tgan"),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_form',
            field=models.CharField(blank=True, help_text='Shartnoma / Grant', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='semester_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='social_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='student_level',
            field=models.CharField(blank=True, help_text='1-kurs, 2-kurs ...', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='student_status',
            field=models.CharField(blank=True, help_text="O'qimoqda / Akademik ta'til ...", max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['hemis_id'], name='accounts_us_hemis_i_19e3bb_idx'),
        ),
    ]
