# Generated by Django 5.2.9 on 2026-03-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_country_user_accommodation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hemis_data_hash',
            field=models.CharField(blank=True, help_text="HEMIS response hash — faqat o'zgarganda update qilish uchun", max_length=64),
        ),
    ]
