# Generated by Django 5.2.12 on 2026-03-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='judge0_token',
        ),
        migrations.AddField(
            model_name='submission',
            name='failed_test_actual',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='failed_test_expected',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='failed_test_input',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='failed_test_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory_used',
            field=models.FloatField(blank=True, help_text='MB da', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time_used',
            field=models.FloatField(blank=True, help_text='Millisekundlarda', null=True),
        ),
    ]
