# Generated by Django 5.2.12 on 2026-03-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_remove_submission_judge0_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='extra_data',
            field=models.JSONField(blank=True, help_text="Run mode test results / qo'shimcha ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='run_type',
            field=models.CharField(choices=[('run', 'Run'), ('submit', 'Submit')], default='submit', max_length=10),
        ),
    ]
