# Generated by Django 5.2.12 on 2026-03-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_language_update'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_user_id_f6f706_idx',
            old_name='submissions_user_prob_created_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_status_fa968c_idx',
            old_name='submissions_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_created_be6fdb_idx',
            old_name='submissions_created_desc_idx',
        ),
    ]
