# Generated by Django 5.2.12 on 2026-03-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_rename_submissions_user_prob_created_idx_submissions_user_id_f6f706_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python', 'Python 3.13'), ('cpp', 'GNU C++ 17'), ('java', 'Java 17'), ('csharp', 'C# (.NET 8)')], max_length=20),
        ),
    ]
